spring:
  application:
    name: Project
  datasource:
    url: jdbc:mysql://localhost:3306/netlink
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
